### ISSUE TITLE
KeyError: "ImageBodyModelEstimator: 'HMRHrNetHead is not in the heads registry'"

### ISSUE THREAD

**Issue by linjing7** [smplbody/hmr-benchmarks#2]
Hi, thanks for your excellent work. When I run the following command, an error occurs: 
`python tools/train.py configs/combine/twins_svt_hmr_mix4_coco_l1.py --work-dir exp/ --gpus 1`
`KeyError: "ImageBodyModelEstimator: 'HMRHrNetHead is not in the heads registry'"`
Could you please upload the HMRHrNetHead?

**Comment by pangyyyyy** [comment]
@linjing7 thanks for pointing that out, I have added it in [92bebb9](https://github.com/smplbody/hmr-benchmarks/commit/92bebb98eb2f530816b7d99a4bd6d94afbab9f8f)

**Comment by smplbody** [comment]
@linjing7 thanks for pointing that out, I have added it in [92bebb9](https://github.com/smplbody/hmr-benchmarks/commit/92bebb98eb2f530816b7d99a4bd6d94afbab9f8f)

**Comment by linjing7** [comment]
Okay, thank you very much.
