### ISSUE TITLE
Checkpoint path not correct

### ISSUE THREAD

**Issue by pixelite1201** [smplbody/hmr-benchmarks#5]
Hello,

Seems like the checkpoint path here https://github.com/smplbody/hmr-benchmarks#downloads for Twin-SVT is not correct: https://drive.google.com/file/d/1ifPYeQY8w-uJzl6yFejaTy_O86OmrjNH/view

It says checkpoint to twin-svt but actually stores resnet checkpoint

**Comment by smplbody** [comment]
@pixelite1201 Hi, thanks for pointing it out. I have checked and updated the links for the twin-svt files and they can also be found in this commit [3713c28](https://github.com/smplbody/hmr-benchmarks/commit/3713c280c1c6d0ef9d32d58a22e7b54bb4ce30cd)
